# <span style="color:green; font-family:Georgia; font-size:0.9m;"> NOM ET PRENOM : DIALLO MAMADOU

# <span style="text-align=center; color:DarkMagenta; font-family:Georgia; font-size:1.2em;"> **   _ M1- TP3 Apprentissage Automatique et Numérique_** </span>


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 1- Préparation des données

In [46]:
import requests
import numpy as np

# <span style="color:green; font-family:Georgia; font-size:0.8em;"> 1. Division de l’échantillon d’apprentissage

In [47]:
fichier = open("house-votes-84.txt", "r")
lignes = fichier.readlines()

# republican = 1 ,democrat = -1 ,y = 1, n = -1 et ? = 0
def choixVote(ch):
    if ch == 'republican':
        return 1
    elif ch == 'democrat':
        return -1
    elif ch == 'y':
        return 1
    elif ch == 'n':
        return -1
    else:
        return 0

In [58]:
Vote = []

i = 0
for ligne in lignes:
    ligne = ligne.replace('\n','')
    t = ligne.split(',')
    for i in range(0,len(t)):
        Vote.append(choixVote(t[i]))

Vote = np.reshape(Vote,(-1,17))
np.random.seed(987654321)
np.random.shuffle(Vote)
print(Vote)

[[ 1 -1  0 ...  1 -1 -1]
 [-1  1 -1 ... -1 -1  1]
 [ 1 -1  1 ...  1 -1 -1]
 ...
 [-1  1 -1 ...  1  1  0]
 [ 1 -1  1 ...  1  0 -1]
 [-1  1 -1 ... -1  1  0]]


In [59]:
Target = Vote[:,0]
Data = Vote[:,1:]

In [65]:
def ajoutSeuil(vect,Data):
    tabRes = np.array([ ( [0]* (len(Data[0])+1) ) ]*len(Data))
    for i in range(0,len(Data)):
        tabRes[i][0]=vect[i]
        for j in range(1,len(tabRes[i])):
            tabRes[i][j] = Data[i][j-1]
    return tabRes


In [66]:
def inversionSigne(Data):
    for i in range(0,len(Data)):
        if(Data[i][0] == (-1)):
            for j in range(1,len(Data[i])):
                Data[i][j] = Data[i][j]*(-1)

In [67]:
nbExempleTrain = 335
TrainData = Data[0:nbExempleTrain,:]
TrainTarget = Target[0:nbExempleTrain]
TrainData = ajoutSeuil(TrainTarget,TrainData)
print(TrainData)
inversionSigne(TrainData)
print("------")
print(TrainData)
print(len(TrainData[0]))

[[ 1 -1  0 ...  1 -1 -1]
 [-1  1 -1 ... -1 -1  1]
 [ 1 -1  1 ...  1 -1 -1]
 ...
 [ 1 -1  1 ...  1 -1 -1]
 [ 1 -1 -1 ...  1 -1  0]
 [-1 -1  1 ... -1  1  1]]
------
[[ 1 -1  0 ...  1 -1 -1]
 [-1 -1  1 ...  1  1 -1]
 [ 1 -1  1 ...  1 -1 -1]
 ...
 [ 1 -1  1 ...  1 -1 -1]
 [ 1 -1 -1 ...  1 -1  0]
 [-1  1 -1 ...  1 -1 -1]]
17


In [68]:
TestData = Data[nbExempleTrain:,:]
TestTarget = Target[nbExempleTrain:]
TestData = ajoutSeuil([1]*len(TestData),TestData)
print(TestData)
print(len(TestData[0]))
print(TestTarget)

[[ 1  1  1 ...  1  1  1]
 [ 1 -1 -1 ... -1  0  1]
 [ 1  1  1 ... -1 -1  1]
 ...
 [ 1  1 -1 ...  1  1  0]
 [ 1 -1  1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1  0]]
17
[-1 -1 -1 -1  1  1  1  1  1 -1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1  1  1 -1
 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1
 -1  1  1 -1  1  1 -1  1  1 -1  1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1  1 -1  1  1 -1 -1  1 -1 -1 -1  1 -1 -1 -1  1  1  1 -1  1  1  1
 -1 -1  1 -1]


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 2- classify

In [73]:
def classify(element,vectPoids):
    res = sum(element * vectPoids)
    if(res >= 0):
        return 1
    return -1

# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 3- test

In [74]:
def test(Data,Target,VectPoids):
    prediction = []
    for i in range(0,len(Data)):
        prediction.append(classify(Data[i],VectPoids))
    nbErreur = 0.0
    for i in range(0,len(Target)):
        if Target[i] != prediction[i]:
            nbErreur += 1
    return nbErreur/len(Target)

# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 4- Train

In [75]:
def negatif(Data,vectPoids):
    return sum(Data*vecteurPoids) < 0


def train(Data,vectPoids,itMax):
    vectPoidsPrec = vectPoids[:]
    nb_bonne_classification_prec = 0
    nb_bonne_classification_cour = 0
    it = 0
    aConverge = False
    #while( (it < itMax) and aConverge == False):
    #print("it :",it)
    #print("itmax :",itMax)
    #print(it < itMax)
    while(it < itMax):
        #print("iteration %i " % it)
        #for i in range(0,len(Data)):
        i=0
        while(i<len(TrainData)):
            #if(negatif(Data[i],vectPoids)):
            result = sum(TrainData[i]*vectPoids)#le resultat de la multiplication vectorielle
            if(result < 0):#si element male classé
                #print("negatif")
                if(nb_bonne_classification_cour > nb_bonne_classification_prec):
                    vectPoidsPrec = vectPoids[:]
                    nb_bonne_classification_prec = nb_bonne_classification_cour
                vectPoids = vectPoids + Data[i]
                nb_bonne_classification_cour = 0
            else:
                #print(nb_bonne_classification_cour)
                nb_bonne_classification_cour += 1
            i += 1
        it += 1
    return vectPoids

In [78]:
#print(range(0,len(TrainData[0])))

vecteurPoids = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
#vecteurPoids = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
print(TrainData)
print(len(TrainData[0]))
print(TestData)
print(len(TestData[0]))

i=0
while(i < 3000):
    #tabIteration.append(i)
    #cacule du meilleur vecteur de poid
    vecteurPoids = train(TrainData,vecteurPoids,i)
    print(vecteurPoids)
    print(test(TestData,TestTarget,vecteurPoids))
    # tabTauxErreur.append(test(testData,vecteurPoids,testTarget))
    
    i=i+10

#i = 0
#while i < 3000:
#    vecteurPoids = train(TrainData,vecteurPoids,i)
#    print(vecteurPoids)
#    print(test(TestData,TestTarget,vecteurPoids))
#    i += 1
#vecteurPoids = train(TrainData,vecteurPoids,20)

[[ 1 -1  0 ...  1 -1 -1]
 [-1 -1  1 ...  1  1 -1]
 [ 1 -1  1 ...  1 -1 -1]
 ...
 [ 1 -1  1 ...  1 -1 -1]
 [ 1 -1 -1 ...  1 -1  0]
 [-1  1 -1 ...  1 -1 -1]]
17
[[ 1  1  1 ...  1  1  1]
 [ 1 -1 -1 ... -1  0  1]
 [ 1  1  1 ... -1 -1  1]
 ...
 [ 1  1 -1 ...  1  1  0]
 [ 1 -1  1 ...  1  0 -1]
 [ 1  1 -1 ... -1  1  0]]
17
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
0.64
[-3 -1 -8 -7 15  3 -4  4  4 -3  4 -2  5 -2 -1 -2 -2]
0.04
[ -4  -2 -15  -9  20   7  -3   5   7  -4   1  -7   5   1  -3  -4  -1]
0.06
[ -5  -1 -18 -11  25   8  -2   6   7  -2   4  -8   5   0  -5  -6  -3]
0.06
[ -5   0 -19 -13  30  10  -4   7   7  -1   4  -8   5   0  -6  -8  -4]
0.06
[ -5   0 -23 -11  30  10  -4   7   7  -2   2  -9   6  -1  -5 -10  -3]
0.09
[ -8  -2 -23 -13  32  11  -5   7   6  -3   3  -7   6  -1  -6  -9  -4]
0.06
[ -4  -3 -26 -14  35   9  -3   8   9  -3   5 -10   6   0  -6  -8  -3]
0.08
[ -6  -3 -28 -12  35  11  -3   6  10  -2   3 -11   4  -1  -6  -8  -2]
0.08
[ -7  -2 -27 -11  36  10  -4   7   9  -1  

KeyboardInterrupt: 