# <span style="color:green; font-family:Georgia; font-size:0.9m;"> NOM ET PRENOM : DIALLO MAMADOU

# <span style="text-align=center; color:DarkMagenta; font-family:Georgia; font-size:1.2em;"> **   _ M1- TP3 Apprentissage Automatique et Numérique_** </span>


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 1- Préparation des données

In [28]:
import requests
import numpy as np
from pylab import *
vote= requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data')
vote = vote.text.replace('\n',',')
vote = vote.replace('republican','1')
vote = vote.replace('democrat','-1')
vote = vote.replace('y','1')
vote = vote.replace('n','-1')
vote = vote.replace('?','0')
vote = vote.split(',')
vote.pop()
vote = np.reshape(vote,(435,17))

np.random.seed(767454868)
np.random.shuffle(vote)

In [34]:
def convertTotabInt(data):

    result = np.array([([0]*len(data[0]))]*len(data))
    i=0
    while(i < len(data)):
        j=0
        while(j<len(data[i])):
            if(int(data[i,j]) == 0):
                result[i,j] = int(0)
            elif(int(data[i,j]) == 1):
                result[i,j] = int(1)
            else:
                result[i,j] = int(-1)

            j=j+1
        i=i+1
    return result

In [35]:
vote = convertTotabInt(vote)

In [41]:
Target = vote[:,0]
Data = vote[:,1:]

#----------- train --------------
trainTarget = Target[0:335]
trainData = Data[0:335]

#----------- test --------------
testTarget = Target[335:435]
testData = Data[335:435]

In [42]:
print(vote)
print (trainTarget)
print (trainData)

[[ 1 -1  1 ...  1 -1 -1]
 [-1  1 -1 ...  1 -1  0]
 [-1  1  1 ...  0  1  1]
 ...
 [-1  1  0 ... -1  1  0]
 [ 1 -1  1 ...  1 -1 -1]
 [ 1 -1  1 ...  1 -1  1]]
[ 1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1  1 -1 -1  1 -1  1 -1  1
 -1 -1 -1  1 -1 -1 -1  1  1  1  1 -1 -1  1 -1  1  1 -1 -1 -1  1 -1  1 -1
  1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1
 -1 -1  1 -1  1 -1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1 -1
 -1  1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1
  1  1 -1 -1 -1  1  1  1 -1  1  1 -1 -1 -1 -1 -1  1  1 -1  1  1 -1  1 -1
  1 -1 -1 -1 -1  1  1  1  1  1 -1 -1 -1  1  1 -1 -1  1  1  1 -1  1 -1  1
 -1  1  1  1 -1  1  1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1  1 -1 -1 -1
  1 -1  1 -1 -1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1 -1  1  1 -1  1 -1 -1  1
 -1  1  1 -1  1 -1  1  1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1 -1 -1 -1
  1 -1  1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1
  1  1  1  1 -1 -1  1  1  1 -1 -1 -1  1 -

In [83]:
vecteurPoids = np.array([1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [84]:
def classify(element,vecteurPoids):

    result = sum(element * vecteurPoids)
    if(result >= 0.5):

        return 1

    return -1

In [85]:
print(classify(trainData[0],vecteurPoids))

-1


# <span style="color:green; font-family:Georgia; font-size:0.8em;"> 1. Division de l’échantillon d’apprentissage