# <span style="color:green; font-family:Georgia; font-size:0.9m;"> NOM ET PRENOM : DIALLO MAMADOU

# <span style="text-align=center; color:DarkMagenta; font-family:Georgia; font-size:1.2em;"> **   _ M1- TP3 Apprentissage Automatique et Numérique_** </span>


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 1- Préparation des données

In [21]:
import requests
import numpy as np

# <span style="color:green; font-family:Georgia; font-size:0.8em;"> 1. Division de l’échantillon d’apprentissage

In [22]:
fichier = open("house-votes-84.txt", "r")
lignes = fichier.readlines()

# republican = 1 ,democrat = -1 ,y = 1, n = -1 et ? = 0
def choixVote(ch):
    if ch == 'republican':
        return 1
    elif ch == 'democrat':
        return -1
    elif ch == 'y':
        return 1
    elif ch == 'n':
        return -1
    else:
        return 0

In [45]:
Vote = []

i = 0
for ligne in lignes:
    ligne = ligne.replace('\n','')
    t = ligne.split(',')
    for i in range(0,len(t)):
        Vote.append(choixVote(t[i]))

Vote = np.reshape(Vote,(-1,17))
np.random.seed(987654321)
np.random.shuffle(Vote)
print(Vote)

[[-1 -1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1]
 [-1 -1  1  1 -1  0  1 -1 -1 -1 -1  1 -1  1 -1 -1  1]
 [-1  1  1  1 -1  1  1 -1 -1 -1 -1  1  0  1  1  1  1]
 [ 1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  0]
 [ 1 -1  1 -1  1  1  1 -1 -1 -1  1  0  1  1  1 -1  1]
 [-1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  0  1  1  1]
 [-1  1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1  0  0]
 [-1  0  1  1  0  1  1 -1 -1 -1 -1  1 -1  1  1 -1 -1]
 [ 1 -1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1  1  0  1]]


In [46]:
Target = Vote[:,0]
Data = Vote[:,1:]

In [47]:
nbExempleTrain = 7
TrainData = Data[0:nbExempleTrain,:]
TrainTarget = Target[0:nbExempleTrain]
print(TrainData)

[[-1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [-1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1]
 [-1  1  1 -1  0  1 -1 -1 -1 -1  1 -1  1 -1 -1  1]
 [ 1  1  1 -1  1  1 -1 -1 -1 -1  1  0  1  1  1  1]
 [-1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  0]
 [-1  1 -1  1  1  1 -1 -1 -1  1  0  1  1  1 -1  1]
 [-1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  0  1  1  1]]


In [48]:
TestData = Data[nbExempleTrain:,:]
TestTarget = Data[nbExempleTrain:]
print(TestData)

[[ 1  1  1 -1 -1 -1  1  1  1 -1 -1 -1 -1 -1  0  0]
 [ 0  1  1  0  1  1 -1 -1 -1 -1  1 -1  1  1 -1 -1]
 [-1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  1  1  0  1]]


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 2- classify

In [49]:
def classify(element,vectPoids):
    res = sum(element * vectPoids)
    if(res >= 0):
        return 1
    return -1

# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 3- test

In [50]:
def test(Data,Target,VectPoids):
    prediction = []
    for i in range(0,len(Data)):
        prediction.append(classify(Data[i],VectPoids))
    nbErreur = 0.0
    for i in range(0,len(Target)):
        if Target[i] != prediction[i]:
            nbErreur += 1
    return nbErreur/len(Target)

# <span style="color:green; font-family:Georgia; font-size:1.5m;"> 4- Train

In [76]:
def train(Data,Target,VectPoids,it_max):
    vectPoidsPrec = VectPoids[:]
    nb_bonne_classification_prec = 0
    nb_bonne_classification_cour = 0
    
    for i in range(0,it_max):
        for j in range(0,len(Data)):
            #print(Data[j])
            if(classify(Data[j],VectPoids) == Target[j]):
                print("class :",classify(Data[j],VectPoids))
                print("tar :",Target[j])
                print("dat :",Data[j])
                if(nb_bonne_classification_cour > nb_bonne_classification_prec):
                    vectPoidsPrec = vecteurPoids[:]
                    nb_bonne_classification_prec = nb_bonne_classification_cour
                
                
        

In [77]:
vecteurPoids = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
vecteurPoids = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
#print(TrainData)
train(TrainData,TrainTarget,vecteurPoids,1)

class : 1
tar : -1
dat : [-1  1  1 -1  1  1 -1 -1 -1 -1 -1 -1  1  1  1  1]
class : 1
tar : 1
dat : [-1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  1]
class : -1
tar : -1
dat : [-1  1  1 -1  0  1 -1 -1 -1 -1  1 -1  1 -1 -1  1]
class : 1
tar : -1
dat : [ 1  1  1 -1  1  1 -1 -1 -1 -1  1  0  1  1  1  1]
class : -1
tar : 1
dat : [-1  1 -1  1  1  1 -1 -1 -1 -1 -1  1  1  1 -1  0]
class : 1
tar : 1
dat : [-1  1 -1  1  1  1 -1 -1 -1  1  0  1  1  1 -1  1]
class : -1
tar : -1
dat : [-1  1 -1  1  1  1 -1 -1 -1 -1 -1 -1  0  1  1  1]
