# <span style="color:green; font-family:Georgia; font-size:0.9m;"> NOM ET PRENOM : DIALLO MAMADOU

# <span style="text-align=center; color:DarkMagenta; font-family:Georgia; font-size:1.2em;"> **   _ M1- TP2 Apprentissage Automatique et Numérique_** </span>


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> Chargement des données

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
iris = datasets.load_iris()
# print (iris.data)
# print (iris.target)
iris_sns = sns.load_dataset("iris")
iris_sns.head()
sns.pairplot(iris_sns, hue='species', height=2.5);

# <span style="color:green; font-family:Georgia; font-size:0.8em;"> 1. Division de l’échantillon d’apprentissage

In [2]:
import numpy as np
Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(987654321)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)

print (shuffledIrisData)
print (shuffledIrisTarget)

[[4.8 3.4 1.6 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.3 4.7 1.6]
 [6.1 2.8 4.7 1.2]
 [5.1 3.8 1.6 0.2]
 [6.6 3.  4.4 1.4]
 [5.8 2.6 4.  1.2]
 [6.6 2.9 4.6 1.3]
 [5.1 2.5 3.  1.1]
 [5.2 3.5 1.5 0.2]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [5.1 3.3 1.7 0.5]
 [7.2 3.6 6.1 2.5]
 [6.4 2.8 5.6 2.2]
 [5.6 2.9 3.6 1.3]
 [6.2 3.4 5.4 2.3]
 [5.1 3.5 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [6.7 3.  5.2 2.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [6.1 2.8 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [5.9 3.  4.2 1.5]
 [4.8 3.  1.4 0.1]
 [4.5 2.3 1.3 0.3]
 [5.5 2.6 4.4 1.2]
 [5.7 2.5 5.  2. ]
 [6.4 3.1 5.5 1.8]
 [6.3 2.9 5.6 1.8]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.3 3.7 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.1 3.5 1.4 0.3]
 [7.7 2.8 6.7 2. ]
 [6.3 2.5 4.9 1.5]
 [6.7 3.1 4.4 1.4]
 [6.  3.4 4.5 1.6]
 [5.7 3.8 1.7 0.3]
 [6.9 3.1 5.4 2.1]
 [6.5 3.  5.8 2.2]
 [5.  3.4 1.6 0.4]
 [4.8 3.4 1.9 0.2]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.8 3.  1.4 0.3]
 [6.1 3.  4.6 1.4]
 [6.7 3.3 5.7 2.5]
 [6.5 3.  5.5 1.8]
 [5.5 2.4 3.

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;">données d'apprentissage </span>

In [3]:
donneesApp = shuffledIrisData[0:100]
targetApp  = shuffledIrisTarget[0:100]
print(donneesApp)
print(targetApp)

[[4.8 3.4 1.6 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.3 4.7 1.6]
 [6.1 2.8 4.7 1.2]
 [5.1 3.8 1.6 0.2]
 [6.6 3.  4.4 1.4]
 [5.8 2.6 4.  1.2]
 [6.6 2.9 4.6 1.3]
 [5.1 2.5 3.  1.1]
 [5.2 3.5 1.5 0.2]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [5.1 3.3 1.7 0.5]
 [7.2 3.6 6.1 2.5]
 [6.4 2.8 5.6 2.2]
 [5.6 2.9 3.6 1.3]
 [6.2 3.4 5.4 2.3]
 [5.1 3.5 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [6.7 3.  5.2 2.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [6.1 2.8 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [5.9 3.  4.2 1.5]
 [4.8 3.  1.4 0.1]
 [4.5 2.3 1.3 0.3]
 [5.5 2.6 4.4 1.2]
 [5.7 2.5 5.  2. ]
 [6.4 3.1 5.5 1.8]
 [6.3 2.9 5.6 1.8]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.3 3.7 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.1 3.5 1.4 0.3]
 [7.7 2.8 6.7 2. ]
 [6.3 2.5 4.9 1.5]
 [6.7 3.1 4.4 1.4]
 [6.  3.4 4.5 1.6]
 [5.7 3.8 1.7 0.3]
 [6.9 3.1 5.4 2.1]
 [6.5 3.  5.8 2.2]
 [5.  3.4 1.6 0.4]
 [4.8 3.4 1.9 0.2]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.8 3.  1.4 0.3]
 [6.1 3.  4.6 1.4]
 [6.7 3.3 5.7 2.5]
 [6.5 3.  5.5 1.8]
 [5.5 2.4 3.

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;">données de dev </span>

In [4]:
donneesDev = shuffledIrisData[100:130]
targetDev  = shuffledIrisTarget[100:130]
print(donneesDev)
print(targetDev)

[[6.  2.2 5.  1.5]
 [6.4 2.7 5.3 1.9]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.5 0.3]
 [6.2 2.9 4.3 1.3]
 [6.2 2.2 4.5 1.5]
 [4.4 3.2 1.3 0.2]
 [4.9 3.1 1.5 0.2]
 [6.  2.7 5.1 1.6]
 [6.3 2.8 5.1 1.5]
 [6.8 3.  5.5 2.1]
 [5.4 3.4 1.7 0.2]
 [6.7 3.  5.  1.7]
 [6.3 3.4 5.6 2.4]
 [5.7 4.4 1.5 0.4]
 [5.2 3.4 1.4 0.2]
 [7.7 2.6 6.9 2.3]
 [4.7 3.2 1.3 0.2]
 [7.  3.2 4.7 1.4]
 [5.7 2.9 4.2 1.3]
 [5.4 3.9 1.7 0.4]
 [6.7 3.1 5.6 2.4]
 [5.5 4.2 1.4 0.2]
 [4.4 3.  1.3 0.2]
 [6.8 2.8 4.8 1.4]
 [7.9 3.8 6.4 2. ]
 [7.7 3.  6.1 2.3]
 [4.4 2.9 1.4 0.2]
 [7.6 3.  6.6 2.1]
 [6.4 2.8 5.6 2.1]]
[2. 2. 0. 0. 1. 1. 0. 0. 1. 2. 2. 0. 1. 2. 0. 0. 2. 0. 1. 1. 0. 2. 0. 0.
 1. 2. 2. 0. 2. 2.]


## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;">données de test </span>

In [5]:
donneesTest = shuffledIrisData[130:150]
targetTest  = shuffledIrisTarget[130:150]
print(donneesTest)
print(targetTest)

[[7.4 2.8 6.1 1.9]
 [4.9 2.5 4.5 1.7]
 [6.9 3.1 4.9 1.5]
 [6.9 3.2 5.7 2.3]
 [5.4 3.7 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [6.  2.9 4.5 1.5]
 [6.7 2.5 5.8 1.8]
 [5.4 3.9 1.3 0.4]
 [5.9 3.2 4.8 1.8]
 [5.7 2.6 3.5 1. ]
 [6.  3.  4.8 1.8]
 [5.4 3.4 1.5 0.4]
 [4.9 3.  1.4 0.2]
 [5.7 2.8 4.1 1.3]
 [5.  3.  1.6 0.2]
 [6.3 2.3 4.4 1.3]
 [7.1 3.  5.9 2.1]
 [5.9 3.  5.1 1.8]
 [5.  3.4 1.5 0.2]]
[2. 2. 1. 2. 0. 2. 1. 2. 0. 1. 1. 2. 0. 0. 1. 0. 1. 2. 2. 0.]


# <span style="color:green; font-family:Georgia; font-size:1.5em;"> 2. Phase d’apprentissage

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;"> 2.1 probabilité à priori </span>

In [6]:
def probAPriori(target,classe):
    cpt = 0
    i=0
    tailleTarget = len(target)
    while i < tailleTarget:
        if target[i] == classe :
            cpt += 1
        i += 1
    return cpt/tailleTarget

In [7]:
PprioriClasse0 = probAPriori(targetApp,0)
PprioriClasse1 = probAPriori(targetApp,1)
PprioriClasse2 = probAPriori(targetApp,2)
print(PprioriClasse0)  # setosa
print(PprioriClasse1)  # versicolor
print(PprioriClasse2)  # virginica

0.32
0.37
0.31


## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;"> 2.2 vraisemblances </span>

In [8]:
def moyenne(mat,target,classe):
    dimension1 = 0.0
    dimension2 = 0.0
    dimension3 = 0.0
    dimension4 = 0.0
    cpt = 0
    i = 0
    while i < len(mat):
        if target[i] == classe :     
            dimension1 += mat[i,0]
            dimension2 += mat[i,1]
            dimension3 += mat[i,2]
            dimension4 += mat[i,3]
            cpt += 1
        i += 1
    dimension1 = dimension1/cpt
    dimension2 = dimension2/cpt
    dimension3 = dimension3/cpt
    dimension4 = dimension4/cpt
    return [dimension1,dimension2,dimension3,dimension4]

In [9]:
vectMoyenClasse0 = moyenne(donneesApp,targetApp,0) # setosa
vectMoyenClasse1 = moyenne(donneesApp,targetApp,1) # versicolor
vectMoyenClasse2 = moyenne(donneesApp,targetApp,2) # virginica

In [10]:
print('-----------------TABLEAU DES Moyennes-----------------')
print('-------------------------------------------------------')
print('CLASSE              0        1          2         3 ')
print('-------------------------------------------------------')
print('0     |           %.3f    %.3f      %.3f      %.3f   '%(vectMoyenClasse0[0],vectMoyenClasse0[1],vectMoyenClasse0[2],vectMoyenClasse0[3]))
print('1     |           %.3f    %.3f      %.3f      %.3f   '%(vectMoyenClasse1[0],vectMoyenClasse1[1],vectMoyenClasse1[2],vectMoyenClasse1[3]))
print('2     |           %.3f    %.3f      %.3f      %.3f   '%(vectMoyenClasse2[0],vectMoyenClasse2[1],vectMoyenClasse2[2],vectMoyenClasse2[3]))

-----------------TABLEAU DES Moyennes-----------------
-------------------------------------------------------
CLASSE              0        1          2         3 
-------------------------------------------------------
0     |           4.972    3.406      1.459      0.231   
1     |           5.830    2.754      4.168      1.289   
2     |           6.545    3.016      5.513      2.029   


In [11]:
def variance(mat,target,y,classe,attr):
    i = 0
    cpt = 0
    res = 0
    while i < len(mat):
        if target[i] == classe :
            res += (mat[i,attr]-y)**2
            cpt += 1
        i += 1
    return res/cpt

In [12]:
varPLClasse0 = variance(donneesApp,targetApp,vectMoyenClasse0[0],0,0) #variance Long. Petale setosa
varPWClasse0 = variance(donneesApp,targetApp,vectMoyenClasse0[1],0,1) #variance Larg. Petale setosa
varSLClasse0 = variance(donneesApp,targetApp,vectMoyenClasse0[2],0,2) #variance Long. sepale setosa
varSWClasse0 = variance(donneesApp,targetApp,vectMoyenClasse0[3],0,3) #variance Larg. Petale setosa
variances0 = [varPLClasse0,varPWClasse0,varSLClasse0,varSWClasse0]
#-----------------------------------------------------------------------------------------------------
varPLClasse1 = variance(donneesApp,targetApp,vectMoyenClasse1[0],1,0) #variance Long. Petale versicolor
varPWClasse1 = variance(donneesApp,targetApp,vectMoyenClasse1[1],1,1) #variance Larg. Petale versicolor
varSLClasse1 = variance(donneesApp,targetApp,vectMoyenClasse1[2],1,2) #variance Long. sepale versicolor
varSWClasse1 = variance(donneesApp,targetApp,vectMoyenClasse1[3],1,3) #variance Larg. Petale versicolor
variances1 = [varPLClasse1,varPWClasse1,varSLClasse1,varSWClasse1]
#-----------------------------------------------------------------------------------------------------
varPLClasse2 = variance(donneesApp,targetApp,vectMoyenClasse2[0],2,0) #variance Long. Petale virginica
varPWClasse2 = variance(donneesApp,targetApp,vectMoyenClasse2[1],2,1) #variance Larg. Petale virginica
varSLClasse2 = variance(donneesApp,targetApp,vectMoyenClasse2[2],2,2) #variance Long. sepale virginica
varSWClasse2 = variance(donneesApp,targetApp,vectMoyenClasse2[3],2,3) #variance Larg. Petale virginica
variances2 = [varPLClasse2,varPWClasse2,varSLClasse2,varSWClasse2]

In [13]:
print('-----------------TABLEAU DES VARIANCES-----------------')
print('-------------------------------------------------------')
print('CLASSE              0        1          2         3 ')
print('-------------------------------------------------------')
print('0     |           %.3f    %.3f      %.3f      %.3f   '%(variances0[0],variances0[1],variances0[2],variances0[3]))
print('1     |           %.3f    %.3f      %.3f      %.3f   '%(variances1[0],variances1[1],variances1[2],variances1[3]))
print('2     |           %.3f    %.3f      %.3f      %.3f   '%(variances2[0],variances2[1],variances2[2],variances2[3]))

-----------------TABLEAU DES VARIANCES-----------------
-------------------------------------------------------
CLASSE              0        1          2         3 
-------------------------------------------------------
0     |           0.103    0.118      0.037      0.009   
1     |           0.238    0.099      0.198      0.033   
2     |           0.277    0.088      0.251      0.070   


In [14]:
import math
def probLoiGauss(x,moyenne,var):
    temp1 = math.pow(x-moyenne,2)/(2*math.pow(var,2))
    temp2 = 1 / (math.sqrt(2*math.pi) * var)
    return temp2 * math.exp(-temp1)

In [15]:
def probAPosteriori(elt,VariablesClasse,aPriori):
    att0 = 2 #Longueur sepale 
    att1 = 3 #Largeur Petale
    resAttr0 = probLoiGauss(elt[att0],VariablesClasse[0][att0],VariablesClasse[1][att0])
    resAttr1 = probLoiGauss(elt[att1],VariablesClasse[0][att1],VariablesClasse[1][att1])
    return aPriori*resAttr0*resAttr1

In [16]:
def classifieur(elt,VariablesClasses0,VariablesClasses1,VariablesClasses2):
    probAPostClasse0 = probAPosteriori(elt,VariablesClasses0,VariablesClasses0[2])
    probAPostClasse1 = probAPosteriori(elt,VariablesClasses1,VariablesClasses1[2])
    probAPostClasse2 = probAPosteriori(elt,VariablesClasses2,VariablesClasses2[2])
    if (probAPostClasse0 > probAPostClasse1) and (probAPostClasse0>probAPostClasse2):
        return 0
    elif (probAPostClasse1 > probAPostClasse0) and (probAPostClasse1>probAPostClasse2):
        return 1
    else:
        return 2

# <span style="color:green; font-family:Georgia; font-size:1.5em;"> 3. Phase de développement

In [17]:
VariablesClasses0 = [vectMoyenClasse0,variances0,PprioriClasse0]
VariablesClasses1 = [vectMoyenClasse1,variances1,PprioriClasse1]
VariablesClasses2 = [vectMoyenClasse2,variances2,PprioriClasse2]
cpt = 0
resClassesDev =[]
while(cpt < len(donneesDev)):
    classe = classifieur(donneesDev[cpt],VariablesClasses0,VariablesClasses1,VariablesClasses2)
    resClassesDev.append(classe)
    cpt += 1

In [18]:
resCorrecteDev=[0,0,0]
resConfusDev=[[0,0,0],[0,0,0],[0,0,0]]
cpt = 0
while(cpt < len(resClassesDev)):
    
    if(resClassesDev[cpt]==0):
        if(targetDev[cpt]==0):
            resCorrecteDev[0] += 1
        elif(targetDev[cpt]==1):
            resConfusDev[0][1]+=1
        else:
            resConfusDev[0][2]+=1
    
    elif(resClassesDev[cpt]==1):
        if(targetDev[cpt]==0):
            resConfusDev[1][0]+=1
        elif(targetDev[cpt]==1):
            resCorrecteDev[1] += 1
        else:
            resConfusDev[1][2]+=1
            
    else:
        if(targetDev[cpt]==0):
            resConfusDev[2][0]+=1
        elif(targetDev[cpt]==1):
            resConfusDev[2][1]+=1
        else:
            resCorrecteDev[2] += 1
    
    cpt += 1


In [19]:
print('---- MATRICE DE CONFUSION SUR LE DEV ----')
print('----------------------------------------')
print('CLASSE            0      1      2   ')
print('-------------------------------------')
print('0     |           %.2d      %.2d      %.2d   '%(resCorrecteDev[0],resConfusDev[0][1],resConfusDev[0][2]))
print('1     |           %.2d      %.2d      %.2d   '%(resConfusDev[1][0],resCorrecteDev[1],resConfusDev[1][2]))
print('2     |           %.2d      %.2d      %.2d   '%(resConfusDev[2][0],resConfusDev[2][1],resCorrecteDev[2]))

---- MATRICE DE CONFUSION SUR LE DEV ----
----------------------------------------
CLASSE            0      1      2   
-------------------------------------
0     |           11      00      00   
1     |           01      05      01   
2     |           00      02      10   


In [20]:
print('bonne réponse %d'%(resCorrecteDev[0]+resCorrecteDev[1]+resCorrecteDev[2]))
print('mauvaise réponse %d'%(resConfusDev[0][1]+resConfusDev[0][2]+resConfusDev[1][0]+resConfusDev[1][2]+resConfusDev[2][0]+resConfusDev[2][1]))

bonne réponse 26
mauvaise réponse 4


In [21]:
print('les attributs les plus précis sont : Longueur sepale et Largeur Petale')

les attributs les plus précis sont : Longueur sepale et Largeur Petale


# <span style="color:green; font-family:Georgia; font-size:1.5em;"> 4. Phase d’évaluation

In [22]:
resClassesTest =[]
cpt = 0
while(cpt < len(donneesTest)):
    classe = classifieur(donneesTest[cpt],VariablesClasses0,VariablesClasses1,VariablesClasses2)
    resClassesTest.append(classe)
    cpt += 1

ResCorrecteTest=[0,0,0]
resConfusTest=[[0,0,0],[0,0,0],[0,0,0]]
cpt = 0
while(cpt < len(resClassesTest)):
    
    if(resClassesTest[cpt]==0):
        if(targetTest[cpt]==0):
            ResCorrecteTest[0] += 1
        elif(targetTest[cpt]==1):
            resConfusTest[0][1]+=1
        else:
            resConfusTest[0][2]+=1
    
    elif(resClassesTest[cpt]==1):
        if(targetTest[cpt]==0):
            resConfusTest[1][0]+=1
        elif(targetTest[cpt]==1):
            ResCorrecteTest[1] += 1
        else:
            resConfusTest[1][2]+=1
    
    else:
        if(targetTest[cpt]==0):
            resConfusTest[2][0]+=1
        elif(targetTest[cpt]==1):
            resConfusTest[2][1]+=1
        else:
            ResCorrecteTest[2] += 1
    
    cpt += 1

In [23]:
print('---- MATRICE DE CONFUSION SUR LE TEST ----')
print('----------------------------------------')
print('CLASSE            0      1      2   ')
print('-------------------------------------')
print('0     |           %.2d      %.2d      %.2d   '%(ResCorrecteTest[0],resConfusTest[0][1],resConfusTest[0][2]))
print('1     |           %.2d      %.2d      %.2d   '%(resConfusTest[1][0],ResCorrecteTest[1],resConfusTest[1][2]))
print('2     |           %.2d      %.2d      %.2d   '%(resConfusTest[2][0],resConfusTest[2][1],ResCorrecteTest[2]))

---- MATRICE DE CONFUSION SUR LE TEST ----
----------------------------------------
CLASSE            0      1      2   
-------------------------------------
0     |           06      00      00   
1     |           00      05      00   
2     |           00      01      08   


In [24]:
print('bonne réponse %d'%(ResCorrecteTest[0]+ResCorrecteTest[1]+ResCorrecteTest[2]))
print('mauvaise réponse %d'%(resConfusTest[0][1]+resConfusTest[0][2]+resConfusTest[1][0]+resConfusTest[1][2]+resConfusTest[2][0]+resConfusTest[2][1]))

bonne réponse 19
mauvaise réponse 1


In [25]:
print('Conclusion : Nous avons q\'une seule mauvaise réponse, un virginica à été confondu à un versicolor')

Conclusion : Nous avons q'une seule mauvaise réponse, un virginica à été confondu à un versicolor
