# <span style="text-align=center; color:DarkMagenta; font-family:Georgia; font-size:1.2em;"> **   _ M1- TP2 Apprentissage Automatique et Numérique_** </span>


# <span style="color:green; font-family:Georgia; font-size:1.5m;"> Chargement des données

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
iris = datasets.load_iris()
# print (iris.data)
# print (iris.target)
iris_sns = sns.load_dataset("iris")
iris_sns.head()
sns.pairplot(iris_sns, hue='species', height=2.5);

ModuleNotFoundError: No module named 'seaborn'

# <span style="color:green; font-family:Georgia; font-size:0.8em;"> 1. Division de l’échantillon d’apprentissage

In [12]:
import numpy as np
Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(987654321)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)

print (shuffledIrisData)
print (shuffledIrisTarget)

NameError: name 'iris' is not defined

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;">données d'apprentissage </span>

In [11]:
donneesApp = shuffledIrisData[0:100]
targetApp  = shuffledIrisTarget[0:100]
print(donneesApp)
print(targetApp)

NameError: name 'shuffledIrisData' is not defined

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;">données de dev </span>

In [10]:
donneesDev = shuffledIrisData[100:130]
targetDev  = shuffledIrisTarget[100:130]
print(donneesDev)
print(targetDev)

NameError: name 'shuffledIrisData' is not defined

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;">données de test </span>

In [104]:
donneesTest = shuffledIrisData[130:150]
targetTest  = shuffledIrisTarget[130:150]
print(donneesTest)
print(targetTest)

[[7.4 2.8 6.1 1.9]
 [4.9 2.5 4.5 1.7]
 [6.9 3.1 4.9 1.5]
 [6.9 3.2 5.7 2.3]
 [5.4 3.7 1.5 0.2]
 [5.8 2.8 5.1 2.4]
 [6.  2.9 4.5 1.5]
 [6.7 2.5 5.8 1.8]
 [5.4 3.9 1.3 0.4]
 [5.9 3.2 4.8 1.8]
 [5.7 2.6 3.5 1. ]
 [6.  3.  4.8 1.8]
 [5.4 3.4 1.5 0.4]
 [4.9 3.  1.4 0.2]
 [5.7 2.8 4.1 1.3]
 [5.  3.  1.6 0.2]
 [6.3 2.3 4.4 1.3]
 [7.1 3.  5.9 2.1]
 [5.9 3.  5.1 1.8]
 [5.  3.4 1.5 0.2]]
[2. 2. 1. 2. 0. 2. 1. 2. 0. 1. 1. 2. 0. 0. 1. 0. 1. 2. 2. 0.]


# <span style="color:green; font-family:Georgia; font-size:0.8em;"> 2. Phase d’apprentissage

## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;"> 2.1 probabilité à priori </span>

In [106]:
def probAPriori(target,classe):
    cpt = 0
    i=0
    tailleTarget = len(target)
    while i < tailleTarget:
        if target[i] == classe :
            cpt += 1
        i += 1
    return cpt/tailleTarget

In [105]:
PprioriClasse0 = probAPriori(targetApp,0)
PprioriClasse1 = probAPriori(targetApp,1)
PprioriClasse2 = probAPriori(targetApp,2)
print(PprioriClasse0)  # setosa
print(PprioriClasse1)  # versicolor
print(PprioriClasse2)  # virginica

0.32
0.37
0.31


## <span style="color:brown; font-family:Gemesorgia; font-size:1.3em;"> 2.2 vraisemblances </span>

In [2]:
def moyenne(mat,target,classe):
    dimension1 = 0.0
    dimension2 = 0.0
    cpt = 0
    i = 0
    while i < len(mat):
        if target[i] == classe :     
            dimension1 += mat[i,0]
            dimension2 += mat[i,1]
            cpt += 1
        i += 1
    dimension1 = dimension1/taille
    dimension2 = dimension1/taille
    matRes = np.asarray([dimension1,dimension2])
    return matRes

In [1]:
vectMoyenClasse0 = moyenne(donneesApp,targetApp,0) # setosa
vectMoyenClasse1 = moyenne(donneesApp,targetApp,1) # versicolor
vectMoyenClasse2 = moyenne(donneesApp,targetApp,2) # virginica

NameError: name 'moyenne' is not defined

In [5]:
def covariance(mat,target,vectM,classe):
    i = 0
    cpt = 0
    covariance = 0
    while i < len(mat):
        if target[i] == classe:
            covariance += (mat[i,0]-vectM[0])+(mat[i,1]-vectM[1])
            cpt += 1
        i += 1
    return covariance/cpt

In [ ]:
covClasse0 = covariance(donneesApp,targetApp,vectMoyenClasse0,0) # setosa
covClasse1 = covariance(donneesApp,targetApp,vectMoyenClasse1,1) # versicolor
covClasse2 = covariance(donneesApp,targetApp,vectMoyenClasse2,2) # virginica

In [3]:
def probLoiGauss(x,moyenne,Mcov):
    temp1 = np.linalg.inv(Mcov)
    temp2 = np.transpose(x-moyenne)
    temp3 = x-moyenne
    resExp = math.exp(-0.5* np.inner(np.inner(temp2,temp1),temp3))
    temp4 = math.pow(np.linalg.norm(Mcov),0.5)
    temp5 = (1 / (2*math.pi* temp4))
    return temp5 * resExp


In [ ]:
def probAPosteriori(elt,VariablesClasses):
    return VariablesClasseO[0]*probLoiGauss(elt,VariablesClasseO[1],VariablesClasseO[2])

In [4]:
def classifieur(elt,VariablesClasses0,VariablesClasses1,VariablesClasses2):
    probAPostClasse0 = probAPosteriori(elt,VariablesClasses0)
    probAPostClasse1 = probAPosteriori(elt,VariablesClasses1)
    probAPostClasse2 = probAPosteriori(elt,VariablesClasses2)
    if(probClasse0 > probClasse1 and probClasse0>probClasse2):
        return 0
    elif(probClasse1 > probClasse0 and probClasse1>probClasse2):
        return 1
    return 2